language: python
sudo: true

os:
  - linux
#  - osx

python:
  - "2.7"
#  - "3.7"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      FILE_OSPATH="MacOSX";
    else
      FILE_OSPATH="Linux";
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2*" ]]; then
      FILE_VERSION="2";
    else
      FILE_VERSION="3";
    fi
  - echo "Using OS $FILE_OSPATH and Python version prefix $FILE_VERSION and python var $TRAVIS_PYTHON_VERSION"
  - export
  - wget https://repo.continuum.io/miniconda/Miniconda${FILE_VERSION}-latest-${FILE_OSPATH}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f environment.yml
  - conda activate scartrek
  - python setup.py install

script:
  - nosetests


deploy:
  provider: pypi
  user: aditi9783
  skip_existing: true
  password:
    secure: L3rXtZIbM7ePBqN/R5qSmG4bX8txhjugJWnAR9WZudZwuLDE7seFefhmHjjNH1spqCcxHDlrJJGNIqS6DxNasIsImkuKsrFbxdhYsrMIB0NyJVdptDNd3tJD17MjxwC3RZwJVoUkjiWA1pLwOovDCnTuQ9CfDXjSRauiJ5zCQ4tEsG/fNrguFEk/QlamXUYNUdqCHoVtW4dcGndmVWCCFF+UeCZnvwqJfOhKZTTTfKcohHKph9eSWVorysIiTNeHbk7Xb1bSi3jokuwzVyWVM5UofsWHFbEAZyFBFPDXQ0OM4ns87k3rrwfe6QPJoMFdrefjRJ4UQObYs0g/XhPlaIEjcu26z4DsQNOIQFuNwjEZRMp5WY2Rm3RZx/A1FYJ0MjF8eqQTcv8ZUvnQzpXDQpRLf1xVwN5tYAlu8apKJFjOFeN8IqnkiRZsnrcooyHymneV3JIPolScXKDD0FO+6F9yMMJJiWBteFsavPlSI1eANyl8BPXStn3MoxqEC2uenUO5oFvZ2V0Mrqh9b3YyV4TeY8TLLix+9t5aYoJ8zb8lsbQkABMTGzTnfLDSZ305k6xc+fRWXnGD90JQ3t7/FxwYTPplb0BrKCUz4hkIlmY44nM9RQo24jyC+MW1ZJPdOhg4UdIFd6WIq9FVmSetREZBn209dTF3fX4OBZhqQYo=
    # via api token
#    secure: aBKjapE744xaRkTkc0IR1lY3HNLrdnnLHM7rivzyWQ7SGwZyYmRd7Ln62F6ri/vbLCa6jXLok08otz9+fhXc8tTXspQQ7oEWM6Wd0YsCmx/eof5CjIrmu5XYH3rsZGXtXjraDj/a/YJEWX/hktUqKWqEJpwI2klgwljyZu3Vf1Hy9wKQA0WAU6Y54ttmbx2dO1YG0HQMubBxVK4swpUJ9F2fbXk4xoHO5HGq9H4SzwQMuTD/tv+TjDgXWH6c/DONkcyxjQNzcmQ6OCgN9Dbt2BDLlL+6psraahTJzWFlTozpxanqR6Dxboj+dfDdm34Xav27k2N122mFtV8o/BPHr7Yf3GZAtwUh69bEJPzU+wVV+D8qe0ljg9x4ptFe+VZSUcj3C9/EvIs6AEPuKSBIxTF+CsxUUCNC2leaerpmLJVW/VoqKHvdIsCJt1hV95JrPlxdg4XM2RJIKZFpdAWaaJNc4ZAFZVViU3COinCI/PLgwd3aRb603GTP8mkqbvgRJCasz5ma1o637esKC0/PG0TCN9KuYde+nG6347AoUy9GZLuqvt1cp2ceEZXw8utt7WtNJrR9o22aQDWZVbFc/JP0ZbW0o1GsqvGZhZRWAkV+VmCCCcs0qANsfyXMZzAZhtr+c6BIoco55HvcKFbzg17V/PACMs9MxMwNVEb1WAw=
#  on:
#    tags: true
  on:
    branch: cibuild
  distributions: sdist bdist_wheel
  python:
    - 2.7
