language: python
sudo: true

os:
  - linux
#  - osx

python:
#  - "3.6"
  - "3.7"
#env:
##  - TRAVIS_PYTHON_VERSION=3.6
#  - TRAVIS_PYTHON_VERSION=3.7

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      FILE_OSPATH="MacOSX";
    else
      FILE_OSPATH="Linux";
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      FILE_VERSION="2";
    else
      FILE_VERSION="3";
    fi
  - wget https://repo.continuum.io/miniconda/Miniconda${FILE_VERSION}-latest-${FILE_OSPATH}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f environment.yml
  - conda activate scartrek
  - python setup.py install

script:
  - nosetests


#deploy:
#  provider: pypi
#  user: aditi9783
#  skip_existing: true
#  password:
#    secure: abcde
#  on:
#    tags: true
#  distributions: sdist bdist_wheel
#  python:
#    - 3.7
